### PR TITLE
Added test case for DB connection

### PR DESCRIPTION
**Pull request by indraneelL**

### CODE REVIEW

**Comment by hvkone** [comment]
Is there a reason you created a dir "test" under the dir "src"? I think that should your test should got in the "sql" dir. What are your thoughts on this?

**Comment by indraneelL** [comment]
> Is there a reason you created a dir "test" under the dir "src"? I think that should your test should got in the "sql" dir. What are your thoughts on this?

yes, we need to create a separate folder for all the test cases which we create for all the modules from now on. You can merge this, on the next push will move to an appropriate folder with other testcases.

**Comment by hvkone** [comment]
Okay sounds good to me. Just wondering why it was in the "src" dir. We can create a new "test" dir.

**Review by Akhilraj03-Github — COMMENTED** [review]
Good work, Indraneel

**Comment by Akhilraj03-Github** [comment]
I have created a new file for testcases, please check and add the  testcases in it @hvkone @indraneelL

**Pull request merged**
